(function(root){
const C={};
C.month=m=>{const [y,n]=m.split('-').map(Number);return y*12+n-1};
C.validMonth=m=>/^\d{4}-(0[1-9]|1[0-2])$/.test(m);
C.validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
C.url=u=>{try{const v=new URL(u);return ['http:','https:'].includes(v.protocol)?v.href:''}catch{return ''}};
C.expand=s=>s.rows.map(r=>({month:r[0],value:r[1],published_at:r[2]||'',edition:r[3]||'reported',source_url:r[4]||s.source_url,provenance:s.provenance}));
C.select=(s,rows,mode='latest')=>{const groups=new Map();for(const r of rows){if(!groups.has(r.month))groups.set(r.month,[]);groups.get(r.month).push(r)}const out=[];for(let list of groups.values()){if(s.group==='PMIs'){if(mode==='flash'){list=list.filter(r=>r.edition==='flash');if(!list.length)continue}else if(mode==='latest'){const finals=list.filter(r=>r.edition==='final');list=finals.length?finals:list.filter(r=>r.edition!=='flash');if(!list.length)continue}}list=[...list].sort((a,b)=>(a.published_at||'').localeCompare(b.published_at||''));if(mode==='first'){const originals=list.filter(r=>['original','reported','final','flash'].includes(r.edition));if(originals.length)list=originals}out.push(mode==='first'?list[0]:list.at(-1))}return out.sort((a,b)=>a.month.localeCompare(b.month))};
C.csv=text=>{text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('Unclosed quoted field');row.push(cell);if(row.some(v=>v!==''))rows.push(row);if(!rows.length)return[];const keys=rows.shift().map(k=>k.trim());if(new Set(keys).size!==keys.length)throw Error('Duplicate CSV columns');return rows.map((r,i)=>{if(r.length!==keys.length)throw Error('CSV column mismatch '+(i+2));return Object.fromEntries(keys.map((k,j)=>[k,r[j]]))})};
C.validate=(rows,ids)=>{if(!rows.length)throw Error('No observations');return rows.map((r,i)=>{if(!ids.includes(r.indicator_id)||!C.validMonth(r.month)||String(r.value??'').trim()===''||!Number.isFinite(Number(r.value)))throw Error('Invalid indicator/month/value: row '+(i+1));if(r.published_at&&!C.validDate(r.published_at))throw Error('Invalid publication date');if(!C.url(r.source_url)&&!String(r.provenance||'').trim())throw Error('A source URL or provenance is required');return {...r,value:Number(r.value),published_at:r.published_at||'',edition:r.edition||'reported',source_url:C.url(r.source_url),provenance:r.provenance||'User import'}})};
C.coverage=rows=>{const months=[...new Set(rows.map(r=>r.month))].sort();return {months:months.length,first:months[0]||'',last:months.at(-1)||'',gaps:months.length?C.month(months.at(-1))-C.month(months[0])+1-months.length:0}};
C.segments=rows=>rows.slice(1).map((r,i)=>[rows[i],r]).filter(([a,b])=>C.month(b.month)-C.month(a.month)===1);
if(typeof module!=='undefined'&&module.exports)module.exports=C;else root.INDICATOR_CORE=C;
})(typeof window!=='undefined'?window:globalThis);
